In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as se

In [3]:
data=pd.read_csv("Social_Network_Ads.csv")

In [4]:
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [5]:
data["Age"].unique()

array([19, 35, 26, 27, 32, 25, 20, 18, 29, 47, 45, 46, 48, 49, 31, 21, 28,
       33, 30, 23, 24, 22, 59, 34, 39, 38, 37, 42, 40, 36, 41, 58, 55, 52,
       60, 56, 53, 50, 51, 57, 44, 43, 54], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split

In [9]:
x=data.drop(['Purchased'],axis=1)
y=data['Purchased']

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [12]:
from sklearn.linear_model import LogisticRegression

In [14]:
logreg=LogisticRegression()

In [15]:
logreg.fit(x_train,y_train)

LogisticRegression()

In [18]:
ytrain_pred=logreg.predict(x_train)
ytest_pred=logreg.predict(x_test)

In [19]:
data=pd.DataFrame(ytrain_pred,y_train)
data=pd.DataFrame(ytest_pred,y_test)

In [21]:
y_pred=logreg.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [22]:
from sklearn.metrics import precision_score,confusion_matrix,accuracy_score,recall_score
cm = confusion_matrix(y_test,y_pred)

In [25]:
cm

array([[58,  0],
       [22,  0]], dtype=int64)

In [23]:
accuracy=accuracy_score(y_test,y_pred)
precision=precision_score(y_test,y_pred,average='micro')
recall=recall_score(y_test,y_pred,average='micro')

In [24]:
print(accuracy)
print(precision)
print(recall)
print(cm)

0.725
0.725
0.725
[[58  0]
 [22  0]]
